config/routes.rb
Historiarenato::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end

  resources :professions

  match 'students/search_for_workshops' => 'students#search_workshops', as: 'search_for_workshops', via: [:get, :post]
  match 'students/search_for_years' => 'students#search_years', as: 'search_for_years', via: [:get, :post]
  match 'students/search_for_observation' => 'students#search_observations', as: 'search_for_observations', via: [:get, :post]
  match 'students/search_general_student' => 'students#search_general', as: 'search_general_student', via: [:get, :post]

  resources :students

  resources :workshops

  resources :lessons

  resources :years

  resources :book_observations

  resources :books
  get 'books/:id/student_observation', to: 'books#students_obs', as: 'student_observation'
  patch '/books/change_students_obs/:id', to: 'books#change_students_obs'

  resources :roles

  resources :disciplines

  resources :servants

  resources :diaries

  resources :student_diaries
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :profession
  has_many :student_books
  has_many :books, :through => :student_books

  has_many :student_diaries
  has_many :diaries, :through => :student_diaries
  #has_and_belongs_to_many :book_observations, join_table: :student_books

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_numericality_of :age, :only_integer => true, :greater_than_or_equal_to => 10

  def self.searchStudentsInWorkshop(workshop_id)
    Student.joins(:books).where(:books => { :workshop_id => workshop_id})
  end

  def self.searchStudentsInYear(year_id)
    Student.joins(books: :year).where(:years => { :id => year_id })
  end

  def self.searchStudentsInObservation(observation_id)
    Student.joins(student_books: :book_observation).where(:book_observations => {:id=>observation_id})
  end

  #parametros
  # bairro - Logradouro do Aluno
  # observation_id - Id da observação de exclusão do aluno de um livro
  # year_id - Ano de matricula do aluno do livro. Ex: 1o elementar
  # turn - Turno da turma que compoe o livro. Ex: Tarde
  # book_id - Id do livro ao qual o aluno está vinculado
  def self.searchGeneral(bairro, observation_id, year_id, turn, workshop_id, book_id)
    query = "SELECT s.* FROM students s "
    query = query + " INNER JOIN student_books sb ON s.id = sb.student_id INNER JOIN books b ON sb.book_id = b.id "

    #busca a observação caso tenha sido selecionada
    if(!observation_id.nil? && observation_id != "")
      query = query + " INNER JOIN book_observations bo ON sb.book_observation_id = bo.id "
    end

    query = query + " WHERE s.name != '' "

    #busca pelo bairro
    if(!bairro.nil? && bairro != "")
    query = query + " AND s.neighborhood ILIKE '%#{bairro}%' "
    end

    #busca a observação caso tenha sido selecionada, caso não tenha sido selecionada, busca por estudantes sem observações
    if(!observation_id.nil? && observation_id != "" && observation_id != 0)
      query = query + " AND sb.book_observation_id = #{observation_id} "
    elsif(!observation_id.nil? && observation_id != "" && observation_id == 0)
      query = query + " AND sb.book_observation_id = null"
    end

    #busca pelo ano do livro, caso tenha sido selecionado
    if(!year_id.nil? && year_id != "")
      query = query + " AND b.year_id = #{year_id}"
    end

    #busca pelo turno do livro, caso tenha sido selecionado
    if(!turn.nil? && turn != "")
      query = query + " AND b.turn ILIKE '%#{turn}%'"
    end

    #busca pelo curso da turma
    if(!workshop_id.nil? && workshop_id != "")
      query = query + " AND b.workshop_id = #{workshop_id}"
    end

    #busca pelo livro
    if(!book_id.nil? && book_id != "")
      query = query + " AND b.id = #{book_id}"
    end

    Student.find_by_sql(query)

  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_profession, only: [ :student_params ]

  def index
    @students = Student.all.order(:name)
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
    @professions = Profession.all.order(:name)
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path, :notice => "Aluno salvo com sucesso"
    else
      @student = Student.new
      @professions = Profession.all.order(:name)
      flash.now[:error] = "O estudante não foi salvo! Verifique os dados e tente novamente!"
      render action: :new
    end

  end

  def edit
    @student = Student.find(params[:id])
    @professions = Profession.all.order(:name)
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to student_path(params[:id]), :notice => "Estudante atualizado!"
    else
      flash.now[:alert] = "Erro na atualização dos dados! Tente novamente!"
      render action: :index
    end
  end

  def destroy
    @student = Student.find(params[:id])

    if @student.destroy
      redirect_to students_path, :notice => "Aluno excluído com sucesso!"
    end
  end

  #Métodos para Relatórios

  def search_workshops
    @workshops = Workshop.all.order(:name)

    if(params[:idworkshop])
      @students = Student.searchStudentsInWorkshop(params[:idworkshop])
      @valorPesquisa = Workshop.find(params[:idworkshop]).name
    else
      @students
      @valorPesquisa
    end
  end

  def search_years
    @years = Year.all.order(:name)

    if(params[:idyear])
      @students = Student.searchStudentsInYear(params[:idyear])
      @valorPesquisa = Year.find(params[:idyear]).name
    else
      @students
      @valorPesquisa
    end

  end

  def search_observations
    @observations = BookObservation.all.order(:name)

    if(params[:idobservation])
      @students = Student.searchStudentsInObservation(params[:idobservation])
      @valorPesquisa = BookObservation.find(params[:idobservation]).name
    else
      @students
      @valorPesquisa
    end
  end

  def search_general

    @observations = BookObservation.all.order(:name)
    #Adicionar Observação nula
    book_observation_null = BookObservation.new
    book_observation_null.name = "SEM EXCLUSÃO"
    book_observation_null.id = 0
    @observations.push(book_observation_null)

    @years = Year.all.order(:name)
    @workshops = Workshop.all.order(:name)
    @books = Book.all.order(:yearbook)

    if(params[:nomelogradouro] || params[:idobservation] || params[:idyear] || params[:nometurno] || params[:idworkshop] || params[:idbook])
      @students = Student.searchGeneral(params[:nomelogradouro],params[:idobservation],params[:idyear],params[:nometurno],params[:idworkshop], params[:idbook])
      @nomelogradouro = params[:nomelogradouro]
      @idobservation = params[:idobservation]
      @idyear = params[:idyear]
      @nometurno = params[:nometurno]
      @idworkshop = params[:idworkshop]
      @idbook = params[:idbook]
    else
      @students
    end

  end

  def student_params
    params.require(:student).permit(
        :name,
        :responsible,
        :age,
        :neighborhood,
        :street,
        :profession_id
    )
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="row">
  <div class="col-sm-6">

    <p><%= link_to "Voltar", students_path, class: "btn btn-primary" %></p>

    <%= form_for @student do |f| %>

        <div class="form-group">
            <%= f.label :name %>
            <div class="row">
              <div class="col-sm-6">
                <%= f.text_field :name, class: "form-control" %>
              </div>
            </div>
        </div>

        <div class="form-group">
          <%= f.label :age %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.number_field :age, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :responsible %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :responsible, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :profession_id %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.collection_select :profession_id, @professions, :id, :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :neighborhood %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :neighborhood, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :street %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :street, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "Salvar", class: "btn btn-success" %>
        </div>

    <% end %>

  </div>
</div>

app/views/students/_search.html.erb
<% if (@students.nil?) %>
    <h3>Resultados (0)</h3>
<% else %>
    <h3>Resultados (<%= @students.count %>)</h3>
    <p>
    <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Idade</th>
        <th>Logradouro</th>
        <th>Created At</th>
        <th>Ver Mais</th>
        <th>Editar</th>
        <th>Deletar</th>
      </tr>

      <% @students.each do |student| %>
          <tr>
            <td><%= student.id %></td>
            <td><%= student.name %></td>
            <td><%= student.age %></td>
            <td><%= student.neighborhood %></td>
            <td><%= time_ago_in_words(student.created_at) %></td>
            <td><%= link_to "Detalhes", student_path(student), class: "btn btn-info" %></td>
            <td><%= link_to "Editar", edit_student_path(student), class: "btn btn-warning" %></td>
            <td><%= link_to "Deletar", student, :confirm => "Tem certeza que deseja excluir esse estudante?", :method => :delete, class: "btn btn-danger" %></td>
          </tr>
      <% end %>
    </table>
    </p>
<% end %>

app/views/students/edit.html.erb
<h1>Editar Aluno</h1>

<p>
  <%= render "form" %>
</p>

app/views/students/index.html.erb
<h1>Alunos <small>Lista</small></h1>
<p><%= link_to "Novo Aluno", new_student_path, class: "btn btn-primary" %></p>

<h3>Relatórios</h3>
<p>
  <%= link_to "Relatório Geral de Alunos", search_general_student_path, class: "btn btn-primary btn-sm" %>
</p>


<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Idade</th>
    <th>Logradouro</th>
    <th>Created At</th>
    <th>Ver Mais</th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

  <% @students.each do |student| %>
      <tr>
        <td><%= student.id %></td>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= student.neighborhood %></td>
        <td><%= time_ago_in_words(student.created_at) %></td>
        <td><%= link_to "Detalhes", student_path(student), class: "btn btn-info" %></td>
        <td><%= link_to "Editar", edit_student_path(student), class: "btn btn-warning" %></td>
        <td><%= link_to "Deletar", student, :confirm => "Tem certeza que deseja excluir esse estudante?", :method => :delete, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
</table>

app/views/students/new.html.erb
<h1>Novo Aluno</h1>

<p>
  <%= render "form" %>
</p>

app/views/students/search_general.html.erb
<h1>Relatório Geral de Alunos</h1>

<p>
<div class="row">
  <div class="col-sm-12">

    <%= form_tag :controller => 'students', :action => 'search_general', :method => 'get' do %>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Livro: </label>
              <%= select_tag 'idbook', options_from_collection_for_select(@books, :id, :complete_name, @idbook), :include_blank => true %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Ano: </label>
              <%= select_tag 'idyear', options_from_collection_for_select(@years, :id, :name, @idyear), :include_blank => true %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Excluído: </label>
              <%= select_tag 'idobservation', options_from_collection_for_select(@observations, :id, :name, @idobservation), :include_blank => true %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Curso: </label>
              <%= select_tag 'idworkshop', options_from_collection_for_select(@workshops, :id, :name, @idworkshop), :include_blank => true %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Logradouro: </label>
              <%= text_field_tag 'nomelogradouro', @nomelogradouro %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Turno: </label>
              <%= text_field_tag 'nometurno', @nometurno  %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= submit_tag "Buscar", :name => nil, class: "btn btn-info" %>
        </div>
    <% end %>

  </div>
</div>
</p>

<p>
  <%= render "search" %>
</p>

app/views/students/search_observations.html.erb
<h1>Relatório de Alunos</h1>

<p>
<div class="row">
  <div class="col-sm-6">

    <%= form_tag :controller => 'students', :action => 'search_observations', :method => 'get' do %>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Excluído: </label>
              <%= select_tag 'idobservation', options_from_collection_for_select(@observations, :id, :name) %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= submit_tag "Buscar", :name => nil, class: "btn btn-info" %>
        </div>
    <% end %>

  </div>
</div>
</p>

<p>
  <%= render "search" %>
</p>

app/views/students/search_workshops.html.erb
<h1>Relatório de Alunos</h1>

<p>
    <div class="row">
      <div class="col-sm-6">

        <%= form_tag :controller => 'students', :action => 'search_workshops', :method => 'get' do %>

            <div class="form-group">
              <div class="row">
                <div class="col-sm-6">
                  <label>Curso: </label>
                  <%= select_tag 'idworkshop', options_from_collection_for_select(@workshops, :id, :name) %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= submit_tag "Buscar", :name => nil, class: "btn btn-info" %>
            </div>
        <% end %>

      </div>
    </div>
</p>

<p>
  <%= render "search" %>
</p>

app/views/students/search_years.html.erb
<h1>Relatório de Alunos</h1>

<p>
<div class="row">
  <div class="col-sm-6">

    <%= form_tag :controller => 'students', :action => 'search_years', :method => 'get' do %>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-6">
              <label>Ano: </label>
              <%= select_tag 'idyear', options_from_collection_for_select(@years, :id, :name) %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= submit_tag "Buscar", :name => nil, class: "btn btn-info" %>
        </div>
    <% end %>

  </div>
</div>
</p>

<p>
  <%= render "search" %>
</p>

app/views/students/show.html.erb
<h1>Detalhes - Aluno</h1>

<p>
  Nome: <%= @student.name %>
</p>

<p>
  Idade: <%= @student.age %>
</p>

<p>
  Responsável: <%= @student.responsible %>
</p>

<p>
  Profissão: <%= @student.profession.name %>
</p>

<p>
  Logradouro: <%= @student.neighborhood %>
</p>

<p>
  Rua: <%= @student.street %>
</p>

<p>
  <%= link_to "Voltar", students_path, class: "btn btn-primary" %>
</p>