config/routes.rb
Historiarenato::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end

  resources :professions

  match 'students/search_for_workshops' => 'students#search_workshops', as: 'search_for_workshops', via: [:get, :post]
  match 'students/search_for_years' => 'students#search_years', as: 'search_for_years', via: [:get, :post]
  match 'students/search_for_observation' => 'students#search_observations', as: 'search_for_observations', via: [:get, :post]
  match 'students/search_general_student' => 'students#search_general', as: 'search_general_student', via: [:get, :post]

  resources :students

  resources :workshops

  resources :lessons

  resources :years

  resources :book_observations

  resources :books
  get 'books/:id/student_observation', to: 'books#students_obs', as: 'student_observation'
  patch '/books/change_students_obs/:id', to: 'books#change_students_obs'

  resources :roles

  resources :disciplines

  resources :servants

  resources :diaries

  resources :student_diaries
  
end

app/models/diary.rb
class Diary < ActiveRecord::Base
  belongs_to :year
  belongs_to :servant
  belongs_to :discipline

  has_many :students, :through => :student_diaries
  has_many :student_diaries
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :authenticate_user!

  def index
    @diaries = Diary.order(:year_id).page(params[:page]).per(10)
  end

  def show
    @diary = Diary.find(params[:id])
    @student_diaries = @diary.student_diaries
  end

  def new
    @diary = Diary.new
    @students = Student.order(:name).all
    @years = Year.order(:name).all
    @disciplines = Discipline.order(:name).all
    @servants = all_teacher_servant
  end

  def create
    diary = Diary.new(diary_params)
    if diary.save
      redirect_to diaries_path, :notice => "Diário cadastrado com sucesso!"
    else
      @diary = Diary.new
      @students = Student.order(:name).all
      @years = Year.order(:name).all
      @disciplines = Discipline.order(:name).all
      @servants = all_teacher_servant
    end
  end

  def edit
    @diary = Diary.find(params[:id])
    @students = Student.order(:name).all
    @years = Year.order(:name).all
    @disciplines = Discipline.order(:name).all
    @servants = all_teacher_servant
  end

  def update
    @diary = Diary.find(params[:id])

    if @diary.update(diary_params)
      redirect_to @diary, :notice => "Diario atualizado"
    else
      flash.now[:alert] = "Erro na atualização dos dados! Tente novamente!"
      render action: :index
    end
  end

  def destroy
    diary = Diary.find(params[:id])

    students = diary.student_diaries
    if diary.destroy
      students.each do |s|
        s.destroy
      end
      redirect_to diaries_path, :notice => "O diário foi excluído com sucesso!"
    end
  end

  private

  def diary_params
    params.require(:diary).permit(
      :year_id,
      :discipline_id,
      :servant_id,
      :student_ids => []
    )
  end

  def all_teacher_servant
    #Buscar servidores professores
    teacher_role = Role.where(name: "Professor")
    servants = Servant.order(:name).all

    servants.each do |serv|
      if !serv.disciplines.include?(teacher_role)
        servants.delete(serv)
      end
    end

    servants
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/views/diaries/_form.html.erb
<div class="row">
  <div class="col-sm-6">

    <p><%= link_to "Voltar", books_path, class: "btn btn-primary" %></p>

    <%= form_for @diary do |f| %>

        <div class="form-group">
          <%= f.label :year %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.collection_select :year_id, @years, :id, :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :discipline %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.collection_select :discipline_id, @disciplines, :id, :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :professor %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.collection_select :servant_id, @servants, :id, :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :students %>
          <div class="row">
            <div class="col-sm-6">
              <%=hidden_field_tag 'diary[student_ids][]'%>
              <% @students.each do |student| %>
                  <p>
                    <%= check_box_tag "diary[student_ids][]", student.id, @diary.students.include?(student) %>
                    <%= student.name %>
                  </p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "Salvar", class: "btn btn-success" %>
        </div>

    <% end %>

  </div>
</div>

app/views/diaries/edit.html.erb
<h1>Editar Diário</h1>

<%= render "form" %>

app/views/diaries/index.html.erb
<h1>Diários <small>Lista</small></h1>
<p><%= link_to "Novo Diário", new_diary_path, class: "btn btn-primary" %></p>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Ano</th>
    <th>Disciplina</th>
    <th>Professor</th>
    <th>Created At</th>
    <th>Ver Mais</th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

  <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.id %></td>
        <td><%= diary.year.name %></td>
        <td><%= diary.discipline.name %></td>
        <td><%= diary.servant.name %></td>
        <td><%= time_ago_in_words(diary.created_at) %></td>
        <td><%= link_to "Detalhes", diary_path(diary), class: "btn btn-info" %></td>
        <td><%= link_to "Editar", edit_diary_path(diary), class: "btn btn-warning" %></td>
        <td><%= link_to "Deletar", diary, :confirm => "Tem certeza que deseja excluir esse diário?", :method => :delete, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
</table>

app/views/diaries/new.html.erb
<h1>Novo Diário</h1>

<%= render "form" %>

app/views/diaries/show.html.erb
<h1>Detalhes - Diário</h1>

<p>
  Ano: <%= @diary.year.name %>
</p>

<p>
  Professor: <%= @diary.servant.name %>
</p>

<p>
  Disciplina: <%= @diary.discipline.name %>
</p>

<p>
    <h6>Alunos</h6>

    <table class="table table-striped">
        <tr>
          <th>Aluno</th>
          <th>Soma F</th>
          <th>Soma C</th>
          <th>Média</th>
          <th>Comportamento</th>
          <th>Aplicação</th>
          <th>Faltas</th>
          <th>Atualizar Dados</th>
          <th>Remover do Diário</th>
        </tr>
        <% @student_diaries.each do |sd| %>
            <tr>
              <td><%= sd.student.name %></td>
              <td><%= sd.value_amount_f %></td>
              <td><%= sd.value_amount_c %></td>
              <td><%= sd.average %></td>
              <td><%= sd.behavior %></td>
              <td><%= sd.application %></td>
              <td><%= sd.absence %></td>
              <td><%= link_to "Atualizar dados", edit_student_diary_path(sd), class: "btn btn-warning" %></td>
              <td><%= link_to "Remover do Diário", sd, :confirm => "Tem certeza que deseja excluir esse estudante deste diário?", :method => :delete, class: "btn btn-danger" %></td>
            </tr>
        <% end %>
    </table>
</p>

<p>
  <%= link_to "Voltar", diaries_path, class: "btn btn-primary" %>
</p>