config/routes.rb
Historiarenato::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end

  resources :professions

  match 'students/search_for_workshops' => 'students#search_workshops', as: 'search_for_workshops', via: [:get, :post]
  match 'students/search_for_years' => 'students#search_years', as: 'search_for_years', via: [:get, :post]
  match 'students/search_for_observation' => 'students#search_observations', as: 'search_for_observations', via: [:get, :post]
  match 'students/search_general_student' => 'students#search_general', as: 'search_general_student', via: [:get, :post]

  resources :students

  resources :workshops

  resources :lessons

  resources :years

  resources :book_observations

  resources :books
  get 'books/:id/student_observation', to: 'books#students_obs', as: 'student_observation'
  patch '/books/change_students_obs/:id', to: 'books#change_students_obs'

  resources :roles

  resources :disciplines

  resources :servants

  resources :diaries

  resources :student_diaries
  
end

app/models/servant.rb
class Servant < ActiveRecord::Base
  has_many :role_servants
  has_many :roles, :through => :role_servants

  has_many :disciplines, :through => :discipline_servants
  has_many :discipline_servants

  has_many :diaries, dependent: :nullify

  CIVIL_STATE = ["", "Casado", "Solteiro", "Viuvo"]

  validates_presence_of :name
  validates_length_of :name, :in => 5..100
  validates_numericality_of :wage, :only_integer => true
end

app/controllers/servants_controller.rb
class ServantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @servants = Servant.order(:name).page(params[:page]).per(10)
  end

  def show
    @servant = Servant.find(params[:id])
    @role_servants = @servant.role_servants
    @discipline_servants = @servant.discipline_servants
  end

  def new
    @servant = Servant.new
    @roles = Role.order(:name).all
    @disciplines = Discipline.order(:name).all
  end

  def create
    servant = Servant.new(servant_params)
    if servant.save
      redirect_to servants_path, :notice => "Servidor cadastrado com sucesso!"
    else
      @servant = Servant.new
      @roles = Role.order(:name).all
      @disciplines = Discipline.order(:name).al
      flash.now[:notice] = "O servidor não foi salvo! Verifique os dados e tente novamente!"
      render action: :new
    end
  end

  def edit
    @servant = Servant.find(params[:id])
    @roles = Role.order(:name).all
    @disciplines = Discipline.order(:name).all
  end

  def update
    @servant = Servant.find(params[:id])

    if @servant.update(servant_params)
      redirect_to @servant, :notice => "Servidor atualizado"
    else
      flash.now[:alert] = "Erro na atualização dos dados! Tente novamente!"
      render action: :index
    end
  end

  def destroy
    servant = Servant.find(params[:id])
    if servant.destroy
      redirect_to servants_path, :notice => "O servidor foi excluído com sucesso!"
    end
  end

  private

  def servant_params
    params.require(:servant).permit(
        :name,
        :year_born,
        :place_of_birth,
        :civil_state,
        :year_in,
        :year_out,
        :obs,
        :wage,
        :role_ids => [],
        :discipline_ids => []
    )
  end
end

app/helpers/servants_helper.rb
module ServantsHelper
end

app/views/servants/_form.html.erb
<div class="row">
  <div class="col-sm-6">

    <p><%= link_to "Voltar", servants_path, class: "btn btn-primary" %></p>

    <%= form_for @servant do |f| %>

        <div class="form-group">
          <%= f.label :name %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :year_born %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.number_field :year_born, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :place_of_birth %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_field :place_of_birth, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :civil_state %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.select :civil_state, Servant::CIVIL_STATE, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :year_in %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.number_field :year_in, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :year_out %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.number_field :year_out, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :roles %>
          <div class="row">
            <div class="col-sm-6">
              <%=hidden_field_tag 'servant[role_ids][]'%>
              <% @roles.each do |role| %>
                  <p>
                    <%= check_box_tag "servant[role_ids][]", role.id, @servant.roles.include?(role) %>
                    <%= role.name %>
                  </p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :wage %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.number_field :wage, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :disciplines %>
          <div class="row">
            <div class="col-sm-6">
              <%=hidden_field_tag 'servant[discipline_ids][]'%>
              <% @disciplines.each do |disc| %>
                  <p>
                    <%= check_box_tag "servant[discipline_ids][]", disc.id, @servant.disciplines.include?(disc) %>
                    <%= disc.name %>
                  </p>
              <% end %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :obs %>
          <div class="row">
            <div class="col-sm-6">
              <%= f.text_area :obs, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.submit "Salvar", class: "btn btn-success" %>
        </div>

    <% end %>

  </div>
</div>

app/views/servants/edit.html.erb
<h1>Editar Servidor</h1>

<p>
  <%= render "form" %>
</p>

app/views/servants/index.html.erb
<h1>Servidores <small>Lista</small></h1>
<p><%= link_to "Novo Servidor", new_servant_path, class: "btn btn-primary" %></p>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Ano de Nascimento</th>
    <th>Naturalidade</th>
    <th>Ano de Ingresso</th>
    <th>Ano de Retirada</th>
    <th>Created At</th>
    <th>Ver Mais</th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

  <% @servants.each do |servant| %>
      <tr>
        <td><%= servant.id %></td>
        <td><%= servant.name %></td>
        <td><%= servant.year_born %></td>
        <td><%= servant.place_of_birth %></td>
        <td><%= servant.year_in %></td>
        <td><%= servant.year_out %></td>
        <td><%= time_ago_in_words(servant.created_at) %></td>
        <td><%= link_to "Detalhes", servant_path(servant), class: "btn btn-info" %></td>
        <td><%= link_to "Editar", edit_servant_path(servant), class: "btn btn-warning" %></td>
        <td><%= link_to "Deletar", servant, :confirm => "Tem certeza que deseja excluir esse servidor??", :method => :delete, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
</table>

app/views/servants/new.html.erb
<h1>Novo Servidor</h1>

<p>
  <%= render "form" %>
</p>

app/views/servants/show.html.erb
<h1>Detalhes - Servidor</h1>

<p>
  Nome: <%= @servant.name %>
</p>

<p>
  Ano de Nascimento: <%= @servant.year_born %>
</p>

<p>
  Naturalidade: <%= @servant.place_of_birth %>
</p>

<p>
  Estado Civil: <%= @servant.civil_state %>
</p>

<p>
  Ano de Ingresso: <%= @servant.year_in %>
</p>

<p>
  Ano de Retirada: <%= @servant.year_out %>
</p>

<p>
<h6>Cargos</h6>
    <ul>
        <% @role_servants.each do |rs| %>
            <li>
              <%= rs.role.name %>
            </li>
        <% end %>
    </ul>
</p>

<p>
  Vencimentos: <%= @servant.wage %>
</p>

<p>
<h6>Disciplinas</h6>
    <ul>
        <% @discipline_servants.each do |ds| %>
            <li>
              <%= ds.discipline.name %>
            </li>
        <% end %>
    </ul>
</p>

<p>
  Observação: <%= @servant.obs %>
</p>

<p>
  <%= link_to "Voltar", servants_path, class: "btn btn-primary" %>
</p>