config/routes.rb
Historiarenato::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
  end

  resources :professions

  match 'students/search_for_workshops' => 'students#search_workshops', as: 'search_for_workshops', via: [:get, :post]
  match 'students/search_for_years' => 'students#search_years', as: 'search_for_years', via: [:get, :post]
  match 'students/search_for_observation' => 'students#search_observations', as: 'search_for_observations', via: [:get, :post]
  match 'students/search_general_student' => 'students#search_general', as: 'search_general_student', via: [:get, :post]

  resources :students

  resources :workshops

  resources :lessons

  resources :years

  resources :book_observations

  resources :books
  get 'books/:id/student_observation', to: 'books#students_obs', as: 'student_observation'
  patch '/books/change_students_obs/:id', to: 'books#change_students_obs'

  resources :roles

  resources :disciplines

  resources :servants

  resources :diaries

  resources :student_diaries
  
end

app/models/book_observation.rb
class BookObservation < ActiveRecord::Base
  has_many :student_books
  has_many :books, :through => :student_books

  has_many :student_diaries
  #has_and_belongs_to_many :students, join_table: :student_books

  validates_presence_of :name
  validates_uniqueness_of :name
  validates_length_of :name, :in => 3..100
end

app/controllers/book_observations_controller.rb
class BookObservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @observations = BookObservation.order(:name).page(params[:page]).per(10)
  end

  def show
    @observation = BookObservation.find(params[:id])
  end

  def new
    @observation = BookObservation.new
  end

  def create
    observation = BookObservation.new(observation_params)

    if observation.save
      redirect_to book_observations_path, :notice => "Observação cadastrada com sucesso!"
    else
      @observation = BookObservation.new
      flash.now[:notice] = "A observação não foi salva! Verifique os dados e tente novamente!"
      render action: :new
    end
  end

  def edit
    @observation = BookObservation.find(params[:id])
  end

  def update
    observation = BookObservation.find(params[:id])

    if observation.update(observation_params)
      redirect_to observation, :notice => "Observação atualizada com sucesso!"
    end
  end

  def destroy
    observation = BookObservation.find(params[:id])
    if observation.destroy
      redirect_to book_observations_path, :notice => "Observação excluída com sucesso!"
    end
  end

  private

  def observation_params
    params.require(:book_observation).permit(
        :name
    )
  end
end

app/helpers/book_observations_helper.rb
module BookObservationsHelper
end

app/views/book_observations/_form.html.erb
<div class="row">

  <div class="col-sm-6">
    <p><%= link_to "Voltar", book_observations_path, class: "btn btn-primary" %></p>

    <%= form_for @observation do |p| %>

        <div class="form-group">
          <%= p.label :name %>
          <div class="row">
            <div class="col-sm-6">
              <%= p.text_field :name, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= p.submit "Salvar", class: "btn btn-success" %>
        </div>

    <% end %>

  </div>
</div>

app/views/book_observations/edit.html.erb
<h1>Editar Observação</h1>

<%= render "form" %>

app/views/book_observations/index.html.erb
<h1>Observações <small>Lista</small></h1>
<p><%= link_to "Nova Observação", new_book_observation_path, class: "btn btn-primary" %></p>

<div class="text-center">
  <p><%= page_entries_info @observations %></p>
  <%= paginate @observations %>
</div>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th>Created At</th>
    <th>Ver Mais</th>
    <th>Editar</th>
    <th>Deletar</th>
  </tr>

  <% @observations.each do |observation| %>
      <tr>
        <td><%= observation.id %></td>
        <td><%= observation.name %></td>
        <td><%= time_ago_in_words(observation.created_at) %></td>
        <td><%= link_to "Detalhes", observation, class: "btn btn-info" %></td>
        <td><%= link_to "Editar", edit_book_observation_path(observation), class: "btn btn-warning" %></td>
        <td><%= link_to "Deletar", observation, :confirm => "Tem certeza que deseja excluir essa observação?", :method => :delete, class: "btn btn-danger" %></td>
      </tr>
  <% end %>
</table>

app/views/book_observations/new.html.erb
<h1>Nova Observação</h1>

<%= render "form" %>

app/views/book_observations/show.html.erb
<h1>Detalhes - Observação</h1>

<br /><br />

<%= @observation.name %> <br />
<%= @observation.created_at %>

<br /><br />

<%= link_to "Voltar", book_observations_path, class: "btn btn-primary" %>